# Generated by Django 3.1.7 on 2021-03-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlines', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('source_link', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('thumbnail', models.CharField(max_length=20, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
