# Generated by Django 3.1.7 on 2021-03-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_suggester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
