# Generated by Django 3.1.7 on 2021-04-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_suggester', '0006_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email_id',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
